#!/usr/bin/env python3
"""Turn rootfs/root/start.sh into the native-boot variant.

Usage: native-start-patch.py <start.sh> <start-native.sh>

The Alpine path ran start.sh with init=/bin/bash, so it set up the network, the
virtual filesystems, the Alpine module loop and sshd itself. Under the native
boot runit already did all that, so those sections are removed. Two problems
specific to the native path are fixed as well: /home is an LVM volume (empty on
a fresh overlay, and still the read-only squashfs when it is not mounted), and
Xorg may already be running from an earlier attempt.
"""

import re
import sys

STORAGE = """
# --- QtCar storage --------------------------------------------------------
# Without a writable /home/tesla the UI fails with "Unable to create folder
# /home/tesla/.Tesla" and then segfaults.
if ! mkdir -p /home/tesla 2>/dev/null || ! touch /home/tesla/.writable 2>/dev/null; then
    echo "storage: /home is not writable, mounting a tmpfs on /home/tesla"
    mount -t tmpfs -o size=512M,mode=0755 tmpfs /home/tesla ||
        echo "storage: ERROR - could not mount a tmpfs on /home/tesla"
fi
rm -f /home/tesla/.writable
mkdir -p /home/tesla/.Tesla/cache /home/tesla/.Tesla/car /home/tesla/.Tesla/data
chown -R tesla:tesla /home/tesla
echo "storage: /home/tesla ready"
"""

XORG = """if [ -e /tmp/.X0-lock ] && DISPLAY=:0 xdpyinfo >/dev/null 2>&1; then
    echo "Xorg: already running on :0, reusing it"
else
    rm -f /tmp/.X0-lock
    /usr/bin/Xorg &
fi"""

HEADER = """#!/bin/bash
# Generated by scripts/lib/native-start-patch.py from rootfs/root/start.sh.
# Native boot: runit already set up the network, the virtual filesystems and
# sshd, so only the QtCar/Xorg/input preparation is left. Run it as root over
# SSH, then start the UI with start-qtcar.sh.
"""

# Sections that only make sense with init=/bin/bash on the Alpine kernel.
DROPS = [
    r"# Network\n(?:ip [^\n]*\n)+",
    r"# With init=/bin/bash[\s\S]*?mount -t devpts[^\n]*\n",
    r"# Mount modloop[\s\S]*?ln -sf /\.modloop[^\n]*\n",
    r"(?m)^/usr/sbin/sshd[^\n]*$\n?",
    r"(?m)^modprobe (?:ehci_pci|ehci_hcd)[^\n]*$\n",
    # prepare-rootfs.sh creates the DRI path in the image; /usr is read-only here.
    r"# Create DRI path symlink[^\n]*\nmkdir -p /usr/lib/x86_64-linux-gnu\nln -sf[^\n]*\n",
    # The Xorg configuration is installed in the image and cannot be rewritten
    # on a read-only squashfs; x11-input-proxy injects the events anyway.
    r'(?m)^ *sed -i "s\|/dev/input/event[01]\|\$(?:TABLET|KBD)_DEV\|"[^\n]*$\n',
]


def main() -> int:
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src).read()

    for pattern in DROPS:
        text = re.sub(pattern, "", text)

    text = re.sub(r"^#!/bin/bash\n", HEADER, text, count=1)

    if "chown -R tesla:tesla /home/tesla\n" in text:
        text = text.replace("chown -R tesla:tesla /home/tesla\n", STORAGE, 1)
    else:
        # Keep working if the upstream script changes.
        text = text.replace(HEADER, HEADER + STORAGE, 1)

    # /opt/games/* is read-only in the native path, and prepare-rootfs.sh has
    # already created what the UI needs, so do not report failures here.
    text = text.replace(
        '    mkdir -p "$path"\n'
        '    chown -hR "$owner" "$path" 2>/dev/null || chown -hR tesla:tesla "$path"\n'
        '    chmod "$mode" "$path"\n',
        '    mkdir -p "$path" 2>/dev/null || return 0\n'
        '    chown -hR "$owner" "$path" 2>/dev/null ||\n'
        '        chown -hR tesla:tesla "$path" 2>/dev/null || true\n'
        '    chmod "$mode" "$path" 2>/dev/null || true\n',
        1,
    )

    if "/usr/bin/Xorg &" in text:
        text = text.replace("/usr/bin/Xorg &", XORG, 1)

    open(dst, "w").write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
